DROP TABLE IF EXISTS AIRWAY_COMPANY;
DROP TABLE IF EXISTS AIRPORT;
DROP TABLE IF EXISTS ROUTE;
DROP TABLE IF EXISTS AIRWAY_FLYING;
DROP TABLE IF EXISTS TICKET;


CREATE TABLE AIRWAY_COMPANY(
ID INT AUTO_INCREMENT  PRIMARY KEY,
CODE VARCHAR2(50),
NAME VARCHAR2(250),
STATUS VARCHAR2(10)
);


CREATE TABLE AIRPORT(
ID INT AUTO_INCREMENT  PRIMARY KEY,
CODE VARCHAR2(50),
NAME VARCHAR2(250),
STATUS VARCHAR2(10)
);


CREATE TABLE  ROUTE(
ID INT AUTO_INCREMENT  PRIMARY KEY,
CODE VARCHAR2(50),
DEPART_FROM VARCHAR2(250),
DESTINATION VARCHAR2(250),
ESTIMATED_FLY_TIME VARCHAR2(10),
STATUS VARCHAR2(10)
);


CREATE TABLE AIRWAY_FLYING(
ID INT AUTO_INCREMENT  PRIMARY KEY,
CODE VARCHAR2(50),
AIRWAY_CODE VARCHAR2(50),
ROUTE_CODE VARCHAR2(50),
QUOTA NUMBER(5),
TICKET_PRICE NUMBER(18,2),
SELL_PRICE NUMBER(18,2),
STATUS VARCHAR2(10)
);

CREATE TABLE TICKET(
ID INT AUTO_INCREMENT  PRIMARY KEY,
CODE VARCHAR2(50),
AIRWAY_CODE VARCHAR2(50),
AIRWAY_FLYING_CODE VARCHAR2(50),
NAME VARCHAR2(250),
PRICE NUMBER(18,2),
FLY_DATE DATE,
CREDIT_CARD VARCHAR2(20),
STATUS VARCHAR2(10)
);